version: "3.8"
services:
  mongo:
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports: 
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/

  # server:
  #   container_name: server-notion-note
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${SERVER_PORT}:${SERVER_PORT}"
  #   depends_on:
  #     - mongo
  #   environment:
  #     - MONGO_HOST=mongo
  #   networks:
  #     - notion-note
  #   command: ["/app/main"]

networks:
  notion-note:
    driver: bridge
