version: "3.8"
services:
  mongo:
    image: mongo:5.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  server:
    container_name: server-notion-note
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    networks:
      - notion-note
    command: ["/app/main"]

networks:
  notion-note:
    driver: bridge
